const correct=["🐸","👹","🦋","🐷"];let entered=[],attempts=0;
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function go(n){$$(".page").forEach(p=>p.classList.remove("active"));$("#page-"+n).classList.add("active");scrollTo({top:0,behavior:"smooth"});if(n===2)animateStats();if(n===6)runMessage();}
$$(".next").forEach(b=>b.onclick=()=>go(+b.dataset.next));
$("#creatures").addEventListener("click",e=>{const b=e.target.closest("button");if(!b)return;const v=b.dataset.v;entered.push(v);b.classList.add("selected");$("#sequence").textContent=entered.map(()=> "♥").join(" ")+" ".repeat(4-entered.length);if(entered.length===4){const ok=entered.every((x,i)=>x===correct[i]);if(ok){$("#access").textContent="ACCESS GRANTED 💗";$("#access").style.color="#ff8fab";heartBurst();$("#continue1").classList.remove("hidden");}else{attempts++;$("#access").textContent=attempts>=3?"Fine. Hint unlocked because you're cute. 🙄":"❌ Wrong. Really? You had ONE job. 😭";if(attempts>=3)$("#access").textContent+="  Start with 🐸.";document.body.classList.add("shake");setTimeout(()=>document.body.classList.remove("shake"),500);entered=[];$("#sequence").textContent="_ _ _ _";$$(".creatures button").forEach(x=>x.classList.remove("selected"));}}});
$("#continue1").onclick=()=>go(2);
const statData=[["Cuteness","97%","97"],["Drama","112%","100"],["Ability to cause chaos","104%","100"],["Replying on time","13%","13"],["Birthday Girl Energy","1000%","100"]];
$("#stats").innerHTML=statData.map(x=>`<div class="stat"><div class="stat-head"><span>${x[0]}</span><b>${x[1]}</b></div><div class="bar"><div class="fill" data-w="${x[2]}"></div></div></div>`).join("");
function animateStats(){$$(".fill").forEach((x,i)=>setTimeout(()=>x.style.width=x.dataset.w+"%",i*180));}
$$(".roast-card").forEach(c=>c.onclick=()=>c.classList.toggle("open"));
const messageLines=["Okay...","Jokes aside.","I actually wanted to tell you something.","I'm genuinely glad I got to know you.","You've brought a lot of laughs, chaos, memories, and good moments into my life.","And I hope this year gives you many more reasons to smile.","Happy Birthday, beautiful. 💗","Stay exactly the way you are.","Well... maybe become 2% less annoying. 😂","But don't change the important parts."];
let msgRun=false;
async function runMessage(){if(msgRun)return;msgRun=true;const box=$("#message");box.innerHTML="";for(const line of messageLines){const d=document.createElement("div");d.textContent=line;d.style.opacity=0;d.style.transform="translateY(15px)";box.appendChild(d);requestAnimationFrame(()=>{d.style.transition=".8s";d.style.opacity=1;d.style.transform="none"});await new Promise(r=>setTimeout(r,1500));}$("#continue6").classList.remove("hidden");}
$("#continue6").onclick=()=>go(7);
$("#openLetter").onclick=()=>{ $("#envelope").classList.add("hidden");$("#finalMessage").classList.remove("hidden");const c=$("#countdown");let n=3;c.textContent=n;const t=setInterval(()=>{n--;if(n===0){clearInterval(t);c.classList.add("hidden");$("#finalReveal").classList.remove("hidden");birthdayExplosion()}else c.textContent=n},900)};
$("#replay").onclick=()=>{msgRun=false;entered=[];attempts=0;$("#continue6").classList.add("hidden");$("#message").innerHTML="";$("#finalReveal").classList.add("hidden");$("#finalMessage").classList.add("hidden");$("#envelope").classList.remove("hidden");$("#countdown").classList.remove("hidden");$("#countdown").textContent="";$$(".creatures button").forEach(x=>x.classList.remove("selected"));$("#sequence").textContent="_ _ _ _";$("#access").textContent="Awaiting birthday girl...";go(1)};
function heartBurst(){for(let i=0;i<35;i++){const p=document.createElement("div");p.className="particle";p.textContent=["💗","💖","✨","💕","🌸"][Math.floor(Math.random()*5)];p.style.left=Math.random()*100+"vw";p.style.top=(40+Math.random()*45)+"vh";p.style.animationDelay=Math.random()*.6+"s";document.body.appendChild(p);setTimeout(()=>p.remove(),3300)}}
function birthdayExplosion(){heartBurst();for(let i=0;i<100;i++){const p=document.createElement("div");p.className="particle";p.textContent=["🎉","✨","💗","🎂","🌸","🥳"][Math.floor(Math.random()*6)];p.style.left=Math.random()*100+"vw";p.style.top=Math.random()*90+"vh";p.style.animationDuration=(2+Math.random()*3)+"s";document.body.appendChild(p);setTimeout(()=>p.remove(),5500)}}
